Realización del objetivo 0
Olasergiolas/Proyecto-IV pull request #1
Opened 2021-09-17 19:16 UTC by Olasergiolas

Creación de la estructura principal del repositorio y del README.md junto con la idea del proyecto.

2021-09-18 05:57 UTC, JJ requested changes
Conviene siempre que en el README.md esté sólo lo que hace falta evaluar. Se suele hablar de "ámbito" o "scope" del mismo; en este caso, poner cosas que están fuera de ámbito hace que falle. Lo siento.

2021-09-18 05:57 UTC, JJ commented on README.md
> +## Lenguaje de programación a utilizar
A partir de aquí, lo que hay no forma parte del objetivo. Es mejor que lo quites, por lo pronto.

2021-09-18 08:28 UTC, Olasergiolas commented on README.md
> +## Lenguaje de programación a utilizar
Sin problema, ya debería de estar todo arreglado.

2021-09-19 06:02 UTC, JJ approved these changes
:musical_note:

2021-09-19 17:11 UTC, merged