Realización del Objetivo-1
Olasergiolas/Proyecto-IV pull request #5
Opened 2021-09-26 17:57 UTC by Olasergiolas

2021-09-28 16:43 UTC, Olasergiolas commented
PR listo para revisión

2021-09-29 06:28 UTC, JJ requested changes
Por favor, consultad el concepto de producto mínimamente viable. Este, aparte de ser un producto, no incluye (ni incluirá en esta asignatura) conceptos de interfaz de usuario como "mostrar". Cada MVP tiene que construirse sobre el anterior, y todos tienen que estar relacionados con la lógica de negocio.
Tu proyecto sigue pareciéndome interesante, pero llegado a este punto no estoy tan seguro de que tenga una lógica de negocio suficiente. En este objetivo tendrías que aclararlo.

2021-09-30 17:31 UTC, Olasergiolas commented
> Por favor, consultad el concepto de producto mínimamente viable. Este, aparte de ser un producto, no incluye (ni incluirá en esta asignatura) conceptos de interfaz de usuario como "mostrar". Cada MVP tiene que construirse sobre el anterior, y todos tienen que estar relacionados con la lógica de negocio. Tu proyecto sigue pareciéndome interesante, pero llegado a este punto no estoy tan seguro de que tenga una lógica de negocio suficiente. En este objetivo tendrías que aclararlo.

Tras intentar entender mejor el concepto de MVP le he dado una vuelta a todo el contenido del objetivo y espero que ahora la lógica de negocio quede algo más clara 👍🏻.

2021-10-01 15:31 UTC, JJ approved these changes
Efectivamente, bastante correcto. Quizás afinar un poco más la release inicial o añadir un PMV0, pero eso ya será cuestión de hablarlo con @agr8, que va ser el equipo de desarrollo en ese hito.

2021-10-01 16:04 UTC, merged